matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '10'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: node_js
      node_js: '10'

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install yarn
    fi
install:
  - yarn
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      yarn dist:linux
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      yarn dist:macos
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn dist:windows
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
