image: Visual Studio 2017

platform:
  - x64

environment:
  GH_TOKEN:
    secure: SIteP5MiOQUmVOwgI1HP2XPDqEYXp2JEQ9iTXX+s6GkFNSWJXnt4+iKcU76UI6RR

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - yarn dist:windows

test: off